language: minimal
install: true

jdk:
  - openjdk8

git:
  depth: 3
  quiet: true

addons:
  ssh_known_hosts: gw.info.unicaen.fr

stages:
  - build
  - name: CI_ops
    if: branch = dmz && type = push

.gradle_template: &gradle
  language: java
  before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  cache:
    directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/

jobs:
  include:
    - <<: *gradle
      stage: build
      before_script:
        - chmod +x ./gradlew
      script:
        - ./gradlew build --scan -s
        - bash <(curl -s https://codecov.io/bash) -t
    - stage: CI_ops
      before_script:
        - curl -# $WEBHOOK_SCRIPT | bash -s new_commit
      script:
        - git remote add master_uplink ssh://git@github.com/$TRAVIS_REPO_SLUG.git
        - git push master_uplink dmz:master
        - git remote remove master_uplink

after_failure: |
  [[ $TRAVIS_EVENT_TYPE == "push" && "master dmz $TRAVIS_TAG" =~ (^|[[:space:]])$TRAVIS_BRANCH($|[[:space:]]) ]] && \
  curl -# $WEBHOOK_SCRIPT | bash -s build_failed

after_success:
  - |
    if [[ $TRAVIS_EVENT_TYPE == "push" && "master $TRAVIS_TAG" =~ (^|[[:space:]])$TRAVIS_BRANCH($|[[:space:]]) ]]; then \
    curl -# $WEBHOOK_SCRIPT | bash -s build_succeeded; fi
  - if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then ssh $FORGE_SYNC || true; fi
